# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

DELETE {{baseUrl}}/products/1/
Content-Type: application/json
###

DELETE {{baseUrl}}/products/2/
Content-Type: application/json
###

DELETE {{baseUrl}}/products/3/
Content-Type: application/json

###
DELETE {{baseUrl}}/products/4/
Content-Type: application/json

###
DELETE {{baseUrl}}/products/5/
Content-Type: application/json
###
DELETE {{baseUrl}}/products/6/
Content-Type: application/json
###
DELETE {{baseUrl}}/products/7/
Content-Type: application/json
###
DELETE {{baseUrl}}/products/8/
Content-Type: application/json
###
DELETE {{baseUrl}}/products/9/
Content-Type: application/json
###
DELETE {{baseUrl}}/products/10/
Content-Type: application/json
###


DELETE {{baseUrl}}/stocks/1/
Content-Type: application/json

###

DELETE {{baseUrl}}/stocks/2/
Content-Type: application/json
###